conference:
  title: International Symposium on Code Generation and Optimization
  short_title: CGO
  year: 2020

previous-conferences:
  - year: 2019
    location: Washington DC
    url: http://cgo.org/cgo2019/
  - year: 2018
    location: Vienna
    url: http://cgo.org/cgo2018/
  - year: 2017
    location: Austin
    url: http://cgo.org/cgo2017/
  - year: 2016
    location: Barcelona
    url: http://cgo.org/cgo2016/
  - year: 2015
    location: San Fransisco
    url: http://cgo.org/cgo2015/
  - year: 2014
    location: Orlando
    url: http://cgo.org/cgo2014/
  - year: 2013
    location: Shenzhen
    url: http://cgo.org/cgo2013/
  - year: 2012
    location: San Jose
    url: http://cgo.org/cgo2012/
  - year: 2011
    location: Chamonix
    url: http://cgo.org/cgo2011/
  - year: 2010
    location: Toronto
    url: http://cgo.org/cgo2010/
  - year: 2009
    location: Seattle
    url: http://cgo.org/cgo2009/
  - year: 2008
    location: Boston
    url: http://cgo.org/cgo2008/
  - year: 2007
    location: San Jose
    url: http://cgo.org/cgo2007/
  - year: 2006
    location: New York
    url: http://cgo.org/cgo2006/
  - year: 2005
    location: San Jose
    url: http://cgo.org/cgo2005/
  - year: 2004
    location: Palo Alto
    url: http://cgo.org/cgo2004/
  - year: 2003
    location: San Francisco
    url: http://cgo.org/cgo2003/

copyright:
  year: 2019-2020

# Where things are
source:       .
destination:  ./_site
layouts_dir:  _layouts

# Handling Reading
exclude:              [
  "*/README.md",
  "Gemfile",
  "Gemfile.lock",
  "README.md"
]
keep_files:           [".git"]
encoding:             "utf-8"
strict_front_matter: false


# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:     /:year/:title/
timezone:      null

quiet:    false
verbose:  false
defaults:
  -
    values:
      layout: "default"

liquid:
  error_mode: warn


kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Extensions
plugins:
  - jekyll-redirect-from  # enable "refirect_from" in front matter

sass:
  style: compressed

